name: Disparo Aniversários

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  disparar:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Rodar script de aniversários
        run: python disparar.py
